//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "metadata_type")]
pub enum MetadataType {
    #[sea_orm(string_value = "attribute")]
    Attribute,
    #[sea_orm(string_value = "entity")]
    Entity,
    #[sea_orm(string_value = "event")]
    Event,
}
