//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use super::sea_orm_active_enums::MetadataType;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    pub metadata_type: MetadataType,
    pub value_type: String,
    pub is_chainable: bool,
    pub is_filterable: bool,
    pub is_sortable: bool,
    pub is_groupable: bool,
    pub is_relation_derived: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub extra: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub delete_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
