//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "metadata_relation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub from_metadata_id: i64,
    pub to_metadata_id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub delete_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Metadata2",
        from = "from_metadata_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub metadata_2: HasOne<super::metadata::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Metadata1",
        from = "to_metadata_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub metadata_1: HasOne<super::metadata::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
