//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "biz_metadata_alias")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub metadata_id: i64,
    pub alias: String,
    pub source: String,
    pub weight: i32,
    pub is_primary: bool,
    pub language: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
