//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "biz_metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "ux_biz_metadata_tenant_code_alive")]
    pub tenant_id: String,
    pub version: i32,
    #[sea_orm(unique_key = "ux_biz_metadata_tenant_code_alive")]
    pub code: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub object_type: String,
    pub parent_id: Option<i64>,
    pub data_class: Option<String>,
    pub value_type: Option<String>,
    pub unit: Option<String>,
    pub status: String,
    pub source: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub biz_metadata: HasOne<Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
